# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "2"
# ///
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `databricks_de_professional`")
spark.sql("USE SCHEMA `bookstore_etl_pro`")

# COMMAND ----------

display(spark.sql("SELECT COUNT(*) FROM bronze"))

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from databricks_de_professional.bookstore_etl_pro.orders_quarentine
